#!/bin/bash
set -a
[ -n "$CTH_VERBOSE" ] && set -x
# Announces build state via Anybar's coloured dot in the menu bar
# Copyright 2016- tobylane. Licensed under the MIT licence found in LICENSE.txt or online
# Usage: Run manually or on schedule with launchctl

ANYBAR_PORT=1739 open -a Anybar.app # Different port, open and direct a new Anybar
anybar () { printf %s "$1" | nc -4u -w0 localhost ${2:-1739}; }
#cd $HOME/Downloads/CorsixTH/build_files # May be needed for launchctl if WorkingDirectory doesn't work
output=$(./cthupdate "$@")
err=$?
anybar question # In progress

if [ "$output" = 'No new changes' ]
then anybar purple # No changes

#elif git diff --name-only HEAD@{1} HEAD | grep -q -e .cmake -e Src -e .txt
#then anybar blue # Lua changes only

elif [ "$err" != "0" ]
then # Git/cmake/xcode/bash failed, narrow it down
	if   ! git pull; then anybar yellow
	elif ! ./cthupdate cmake; then anybar orange
	elif ! ./cthupdate xcode; then anybar red
	else anybar black
	fi

elif [ "$err" = "0" ]
then anybar green # Successful new build
	if git describe --tags --contains HEAD@{1} > /dev/null 2>&1
		then anybar cyan # Release
	fi

else
	echo "error was not 0 and not not 0"
	anybar exclamation
fi
