#!/bin/bash
set -a
[ -n "$CTH_VERBOSE" ] && set -x
# Announces build state via Anybar's coloured dot in the menu bar
# Copyright 2016- tobylane. Licensed under the MIT licence found in LICENSE.txt or online
# Requires Anybar: brew cask install anybar or https://github.com/tonsky/AnyBar
# Usage: Run manually or on schedule with launchctl

ANYBAR_PORT=1739 open -a Anybar # Different port, open and direct Anybar
anybar () { printf %s "$1" | nc -4u -w0 localhost "${2:-1739}"; }
#cd $HOME/Downloads/CorsixTH/build_files # May be needed for launchctl if WorkingDirectory doesn't work
cd "$(git rev-parse --show-toplevel)"
output=$(build_files/cthupdate "$@")
err=$?
set -e
anybar question # In progress

if [ "$output" = 'No new changes.' ]
then anybar purple # No changes

#elif git diff --name-only HEAD@{1} HEAD | grep -q -e .cmake -e Src -e .txt
#then anybar blue # Lua changes only

elif [ "$err" != "0" ]
then # Git/cmake/xcode/bash failed, narrow it down
	if   ! git pull --ff-only; then anybar yellow
	elif ! build_files/cthupdate cmake; then anybar orange
	elif ! build_files/cthupdate make; then anybar red
	else anybar black
	fi

elif [ "$err" = "0" ]
then anybar green # Successful new build
	if git describe --tags --contains 'HEAD@{1}' > /dev/null 2>&1
		then anybar cyan # Release
	fi

else
	echo "error was not 0 and not not 0"
	anybar exclamation
fi
