#!/bin/bash
set -ea
[ -n "$CTH_VERBOSE" ] && set -x
# Package up the app into given format - (default) xz = 7.9mb, zip = 11.2mb, folder = 29.2mb, dmg = 11.2mb
# Not including AnimView.app of 8.3mb. Without dependencies xz = 1.5mb, zip = 2.3mb, folder = 7.8mb, dmg = 2.8mb
# Copyright 2016- tobylane. Licensed under the MIT licence found in LICENSE.txt or online
# Usage: cthpackage [ xz | zip | folder | dmg ] [ release ] [ upload ]

if [ "$(basename "$(pwd)")" = "build_files" ]; then cd ..; fi

# git checkout upstream # Uncomment these two lines if used in cthupdate:17
folder=CorsixTH-mac-$(git rev-parse --short HEAD)
if [ "$2" = "release" ] && git describe --tags --contains HEAD@{1} > /dev/null 2>&1
	then folder=CorsixTH-mac-$(git describe --tags --contains HEAD@{1})
fi
# git checkout - # To return to the previous branch

rsync -a CorsixTH.app ..
cd ../

if [ "$1" = 'xz' ] || ! [ $1 ]
then
	file="$folder.tar.xz"
	XZ_OPT=-7 tar cJf "$file" CorsixTH.app
elif [ "$1" = "zip" ]
then
	file="$folder.zip"
	zip -qro9 "$file" CorsixTH.app
elif [ "$1" = "dmg" ]
then
	name="$(echo $folder | sed 's/-mac-/ /')" # "CorsixTH commit/tag"
	file="$name".dmg
	CorsixTH/build_files/create-dmg/create-dmg --background CorsixTH/build_files/CthDmgBackground.png \
	 --volname "$name" --volicon CorsixTH/CorsixTH/Icon.icns --icon-size 48 --window-size 600 337 \
	 --text-size 12 --icon CorsixTH 76 151 --app-drop-link 224 151 "$name".dmg CorsixTH.app/ > /dev/null
else
	file="$folder"
	rsync -a CorsixTH.app "$folder".app
	exit # Currently nothing else will be done to a folder
fi

if [ "$2" = "upload" ] || [ "$3" = "upload" ]
then
	curl --progress-bar --upload-file "$file" https://transfer.sh/"$file" | pbcopy
	echo "$(pbpaste) in clipboard"
fi

openssl dgst -sha256 "$file" > "$file".sha256
cat "$file".sha256
rm -rf "$folder"
