#!/bin/bash
set -ea
# Script to pull from github all updates, if any cmake then rerun cmake and xcode, if any c++ then rerun xcode,
# else the lua/bitmap/etc updates are in, saving the previous app
# brew update && brew upgrade # A good idea every so often, brew outdated to see what upgrade will do
# Usage: cthupdate [ clean | build [ package [ xz | zip | folder | dmg ] [ upload ] ] ]

lua=5.3 # 5.1 5.2 5.3
changelog=0 # 0 1

if [ $1 = "clean" ]
then xcodebuild -configuration Release clean > /dev/null && cd CorsixTH && xcodebuild -configuration Release clean > /dev/null
	 cd ../ && rm CMakeCache.txt || true && echo "Cleaned" && exit 0
fi

if [[ $(git pull) == "Already up-to-date." ]] && [[ $1 != "build" ]]
then
	echo "No new changes"
	exit 0
fi

echo
if [[ $(git diff --name-only ORIG_HEAD HEAD) == *.cmake* ]] || [[ $1 == 'build' ]]
then
	# Adjust this path if CMake is elsewhere, eg /Applications/CMake.app/Contents/bin/cmake
	~/Applications/CMake.app/Contents/bin/cmake . -G Xcode \
-DLUA_PROGRAM_PATH=$(which lua"$lua") -DLUA_INCLUDE_DIR=/usr/local/include/lua"$lua"/ -DLUA_LIBRARY=/usr/local/lib/liblua."$lua".dylib
fi

if [[ $(git diff --name-only ORIG_HEAD HEAD) =~ (.cmake|Src|.txt) ]] || [[ $1 == 'build' ]]
then
	cd CorsixTH/
	find . -prune -name "CorsixTH-*.app" ! -name "CorsixTH-$(git rev-parse --short ORIG_HEAD).app" -exec rm -rf {} \;
	rsync -a CorsixTH.app/ CorsixTH-$(git rev-parse --short ORIG_HEAD).app || true
	xcodebuild -configuration Release > /dev/null
	rsync -a --remove-source-files --delete --force Release/CorsixTH.app .
	# Maybe these lines go in cmake/xcode/post-build, take out from here when that's done
	rsync -a ../README.txt ../LICENSE.txt ../CONTRIBUTING.txt CorsixTH.app/
	rsync -a CorsixTH.app/Contents/Resources/. CorsixTH.app/Contents/MacOS/
	rm -rf CorsixTH.app/Contents/Resources/
	
	cd ../
fi

echo "Updated to $(git rev-parse --short HEAD)"
if [ $changelog -eq 1 ]
then
	git --no-pager log --oneline --color -n 10 $(git rev-parse --short ORIG_HEAD) HEAD
	printf ""
fi

if [[ $2 = package ]]
then ./cthpackage ${@:3}
fi
