#!/bin/sh -x
# git name-rev is fail
CURRENT=`git branch | grep '\*' | awk '{print $2}'`
git checkout master || exit 1
git pull origin master || exit 1
git checkout ${CURRENT} || exit 1
git rebase master || exit 1