#!/bin/sh -x
# git name-rev is fail
CURRENT=`git branch | grep '\*' | awk '{print $2}'`
git checkout master || exit 1
git merge ${CURRENT} || exit 1
git push origin master
git checkout ${CURRENT} || exit 1